<a href="https://colab.research.google.com/github/devkakeri06/DAL_practicals/blob/main/DAL_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'c1':[22,33,11,87], 'c2':[34,56,69,np.nan], 'c3':[np.nan,34,55,32], 'c4':[67,99,np.nan, 100]})
# print(df1)

In [7]:
df1.isna()

      c1     c2     c3     c4
0  False  False   True  False
1  False  False  False  False
2  False  False  False   True
3  False   True  False  False

In [8]:
df1.dropna()

   c1    c2    c3    c4
1  33  56.0  34.0  99.0

In [9]:
df1.fillna(value='NA')

   c1    c2    c3     c4
0  22  34.0    NA   67.0
1  33  56.0  34.0   99.0
2  11  69.0  55.0     NA
3  87    NA  32.0  100.0

In [10]:
df1.dtypes

c1      int64
c2    float64
c3    float64
c4    float64
dtype: object